"""Demo seed fixtures for POST /demo/seed.

The fixtures are REAL agent output: each visible meal was logged through the live
pipeline (parse → USDA lookup → portion estimate → online eval) and its exact
``per_item`` / ``totals`` / ``trace`` / quality eval captured into a per-persona
JSON file. Nothing here is hand-authored — the confidence is the genuine mean of
the four eval axes, so the "why this confidence" breakdown adds up. Loading the
canned data keeps /demo/seed deterministic and offline (no Gemini call, no spend).

Three selectable personas (the persona loader, ): an **endurance runner** who
under-logs her training carbs, a **bodybuilder** who under-logs his post-lift
protein portions, and a generalist **busy professional** whose eaten-out portions
run bigger than he logs (so a non-athlete judge sees themselves). Each ships a
visible day + the learning-loop seed (confirmed meals as the held-out gate set + a
couple of corrections) so a judge can hit "retune" immediately and watch the gate
ship a persona-specific rule.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

_DIR = Path(__file__).parent


def _load(filename: str) -> dict[str, Any]:
    return json.loads((_DIR / filename).read_text(encoding="utf-8"))


def _load_meals(filename: str) -> list[dict[str, Any]]:
    """Load a persona's captured visible day: each meal is ``{text, totals,
    detail}`` — the same shape ``/demo/seed`` feeds to ``log_store.add``."""
    return _load(filename)["meals"]


def _load_previous_day(filename: str) -> list[dict[str, Any]]:
    """Load the simulated previous day: a full day of real agent logs (each
    ``{text, totals, detail}``); dataset-point meals carry ``detail.dataset_point``
    and show their held-out true value (generated by tools/gen_demo_data.py)."""
    return _load(filename).get("previous_day", [])


def _load_confirmations(filename: str) -> list[dict[str, Any]]:
    """Derive the held-out test set from the previous day's dataset-point meals.

    Each confirmation is ``{meal_text, items, totals}`` carrying full per-item
    detail; the totals are the agent's USDA-grounded estimate of a precise spec
    of that meal — the real ground truth, not a hand-typed number."""
    return [
        {
            "meal_text": m["text"],
            "items": m.get("detail", {}).get("per_item", []),
            "totals": m["totals"],
        }
        for m in _load_previous_day(filename)
        if m.get("dataset_point")
    ]


@dataclass(frozen=True)
class Persona:
    """One selectable demo persona: a visible day + a learning-loop seed."""

    key: str
    label: str           # short name for the picker ("Endurance runner")
    blurb: str           # one-line description for the picker
    goals: dict[str, float]
    goal_rationale: str
    # The on-screen under-count to correct — a substring of one visible meal,
    # plus a plain-words description of the deviation, for the explainer modal.
    hook_meal: str
    hook_note: str
    # What a retune should learn (shown in the explainer so the payoff is clear).
    learns: str
    # The user's freeform "goals + eating style" — standing context for the
    # corrector, so its rules reflect who this person is.
    profile: str = ""
    meals: list[dict[str, Any]] = field(default_factory=list)
    # The full simulated previous day (real agent logs); a subset are dataset points.
    previous_day: list[dict[str, Any]] = field(default_factory=list)
    confirmations: list[dict[str, Any]] = field(default_factory=list)
    feedback: list[dict[str, Any]] = field(default_factory=list)


# ──────────────────────────────────────────────────────────────────────────────
# Persona A — Endurance runner (CARBS). The big plate of spaghetti is logged at
# ~196 kcal, the visible carb under-count to correct.
# ──────────────────────────────────────────────────────────────────────────────

RUNNER = Persona(
    key="runner",
    label="Endurance runner",
    blurb="Carbs up big before runs, eats heavy protein to recover after.",
    goals={"208": 2400.0, "203": 150.0, "205": 300.0, "204": 70.0},
    goal_rationale=(
        "Sample targets for a marathon runner (~2 400 kcal/day, carb-forward with "
        "real protein needs). The agent under-counts her around training — both her "
        "pre-run carbs and her post-run recovery protein. Correct one in plain "
        "words, then re-tune to watch it learn the pattern."
    ),
    hook_meal="spaghetti",
    hook_note=(
        "Two visible under-counts: the big plate of spaghetti before her run "
        "(~196 kcal — her pre-run carbs) and the post-run beef chili (~14 g "
        "protein — her recovery protein). Correct either, then re-tune."
    ),
    learns="Around training her portions run big — carbs before runs, protein after.",
    profile=(
        "I'm a marathon runner in a lean cut. I carb-load hard before long runs "
        "and races, and I eat big protein portions after a run to recover and hold "
        "muscle while I'm burning a lot of mileage."
    ),
    meals=_load_meals("demo_seed_data.json"),
    previous_day=_load_previous_day("demo_seed_data.json"),
    # Held-out test set, derived from the previous day's dataset-point meals
    # (real agent output, validated live): pre-run she carb-loads, post-run she
    # eats heavy protein — both well above the agent's default servings, while the
    # plain lunch guard must stay put.
    confirmations=_load_confirmations("demo_seed_data.json"),
    feedback=[
        # Facet 1: pre-run carbs run high.
        {"feedback_text": "my pre-run oats are way bigger than this — closer to 90 g of carbs",
         "meal_text": "oatmeal before my morning run"},
        # Facet 2: post-run recovery runs high on BOTH protein and fats.
        {"feedback_text": "after a long run my recovery meals are way bigger — nearly "
                          "double the protein, plus a lot more healthy fat like avocado "
                          "and olive oil",
         "meal_text": "a grilled chicken bowl with avocado after my long run"},
    ],
)


# ──────────────────────────────────────────────────────────────────────────────
# Persona B — Bodybuilder (PROTEIN portions). The "big serving of ground turkey
# after lifting" logs at ~28 g protein, the visible post-lift under-count.
# ──────────────────────────────────────────────────────────────────────────────

BODYBUILDER = Persona(
    key="bodybuilder",
    label="Bodybuilder",
    blurb="Under-logs his post-lift protein portions — teach it his big servings.",
    goals={"208": 3000.0, "203": 220.0, "205": 300.0, "204": 80.0},
    goal_rationale=(
        "Sample targets for a bodybuilder in a lean bulk (~3 000 kcal/day, "
        "protein-forward). The agent under-portions his post-lift protein — "
        "correct one in plain words, then re-tune to watch it learn his "
        "after-lifting servings."
    ),
    hook_meal="ground turkey",
    hook_note=(
        "The big serving of ground turkey after lifting logged at ~28 g protein "
        "— a small portion's worth. That's the on-screen under-count to correct."
    ),
    learns="After lifting, his protein portions are about double the default.",
    profile=(
        "I'm a bodybuilder on a lean bulk. I lift heavy and eat large protein "
        "portions after training to grow — I track protein closely and my "
        "post-lift servings are bigger than a normal plate."
    ),
    meals=_load_meals("demo_seed_bodybuilder.json"),
    previous_day=_load_previous_day("demo_seed_bodybuilder.json"),
    # Held-out test set, derived from the previous day's dataset-point meals (real
    # agent output): post-lift protein meals the agent under-portions (the pattern
    # to learn), plus non-workout guards the learned rule must NOT change.
    confirmations=_load_confirmations("demo_seed_bodybuilder.json"),
    feedback=[
        # Post-lift protein runs big. Corrections are on meals that are NOT held-out
        # dataset points (kept DISJOINT, like the runner's), so the corrector never
        # learns from a meal it's then graded on — the gate stays honest.
        {"feedback_text": "after lifting I eat way more protein than this — my post-workout "
                          "chicken is more like 10-12 oz, not a small serving",
         "meal_text": "a post-lift chicken and rice bowl"},
        {"feedback_text": "my post-workout protein shakes are double scoops — way more "
                          "protein than you logged",
         "meal_text": "a protein shake after lifting"},
    ],
)


# ──────────────────────────────────────────────────────────────────────────────
# Persona C — Busy professional (EATING-OUT portion creep). The generalist, non-
# athlete persona: a chicken burrito bowl grabbed for lunch logs small because the
# restaurant portion is much bigger than the default serving — the visible
# under-count. Eating out a few times a week is where his tracking drifts.
# ──────────────────────────────────────────────────────────────────────────────

EVERYDAY = Persona(
    key="everyday",
    label="Busy professional",
    blurb="Eats out a few times a week — those portions run bigger than he logs.",
    goals={"208": 2000.0, "203": 150.0, "205": 195.0, "204": 68.0},
    goal_rationale=(
        "Sample targets for a busy professional with moderate activity, eating "
        "healthier to lose a little fat and put on a bit of muscle — a gentle "
        "recomp, not an extreme cut (~2 000 kcal/day, balanced macros with enough "
        "protein for muscle, not an athlete's split). The agent under-counts the "
        "meals he eats out, where restaurant and takeout portions run bigger than a "
        "home-cooked plate. Correct one in plain words, then re-tune to watch it "
        "learn the pattern."
    ),
    hook_meal="chicken and rice bowl",
    hook_note=(
        "The chicken and rice bowl he grabbed for lunch logged small — the takeout "
        "portion is bigger than the default serving (more rice and more chicken than "
        "he'd plate at home). That's the on-screen under-count to correct."
    ),
    learns=(
        "When he eats out, his portions run bigger than the default — more rice "
        "and larger servings."
    ),
    profile=(
        "I'm a busy professional with a moderately active routine, eating a bit "
        "healthier to lose a little fat and put on some muscle — nothing extreme, "
        "just getting fitter. I cook simple meals when I can, but I eat out or order "
        "takeout a few times a week, and those portions are bigger than what I'd "
        "make at home."
    ),
    meals=_load_meals("demo_seed_everyday.json"),
    previous_day=_load_previous_day("demo_seed_everyday.json"),
    # Held-out test set, derived from the previous day's dataset-point meals (real
    # agent output): the eaten-out meals the agent under-portions (the pattern to
    # learn), plus a plain home meal guard the learned rule must NOT change.
    confirmations=_load_confirmations("demo_seed_everyday.json"),
    feedback=[
        # Eating out runs big — two distinct restaurant/takeout meals. Corrections
        # target meals that are NOT held-out dataset points (kept DISJOINT, like the
        # other personas), so the corrector never learns from a meal it's then graded
        # on — the gate stays honest.
        {"feedback_text": "the place piles it on — way more rice and chicken than "
                          "this; the restaurant portion is bigger than what I'd plate "
                          "at home",
         "meal_text": "a chicken burrito I grabbed for lunch"},
        {"feedback_text": "takeout always runs bigger than I log — easily another cup "
                          "of noodles and a larger serving than a home-cooked plate",
         "meal_text": "lo mein takeout for dinner"},
    ],
)


# ──────────────────────────────────────────────────────────────────────────────
# Persona D — The creator's log (REAL dogfooded account). Not a story: these are
# the creator's own meals, corrections, and confirmed dataset points, exported
# from a live account and replayed verbatim. Calorie-dense, carb-forward days
# around morning lifts; the corrections are his actual "that portion runs big"
# notes (sourdough, honey, oats, post-workout carbs).
# ──────────────────────────────────────────────────────────────────────────────

CREATOR = Persona(
    key="creator",
    label="The creator's log",
    blurb="A real dogfooded account — actual meals, corrections, and confirmed dataset points.",
    goals={"208": 2635.0, "203": 230.6, "205": 230.6, "204": 87.8},
    goal_rationale=(
        "The creator's own targets, straight from his account: Mifflin–St Jeor "
        "BMR 1650 kcal × 1.9 (very active) = TDEE 3135 kcal, with a 500 kcal "
        "deficit → a 2635 kcal cut, carbs kept high enough for training and "
        "plenty of protein. These meals are his real logs — correct one in plain "
        "words, then re-tune to watch it learn his portions."
    ),
    hook_meal="overnight oats",
    hook_note=(
        "The overnight oats logged with more carbs than he actually eats — his "
        "oats run closer to 50 g, not the bowl the default assumed. That's a real "
        "on-screen under-count he corrected; pick it (or any visible meal) and re-tune."
    ),
    learns=(
        "His real portions: sourdough and honey run smaller than the default, "
        "his oats are about 50 g, and his post-workout carbs run higher."
    ),
    profile=(
        "I'm mostly focused on building muscle and maintaining a lean physique. I "
        "usually lift in the morning and walk a bunch throughout the day. I went on "
        "two aggressive cuts in november and april. I just went on a solo trip to "
        "europe and gained more fat than I would've liked (10lbs). I haven't been in "
        "a muscle building phase in a while, but I also want to lose some fat from "
        "the trip. So I'm aiming to do a small deficit while keeping carbs high "
        "enough for adequate performance and recovery. And sufficient protein and fats."
    ),
    meals=_load_meals("demo_seed_creator.json"),
    previous_day=_load_previous_day("demo_seed_creator.json"),
    # Held-out test set: the meals the creator actually confirmed as dataset points
    # (his preworkout dates + his ground-beef salad), carried verbatim from the
    # account snapshot.
    confirmations=_load_confirmations("demo_seed_creator.json"),
    feedback=[
        # The creator's real corrections, replayed verbatim. Each targets a visible
        # meal that is NOT a held-out dataset point, so the corrector never learns
        # from a meal it's then graded on (kept DISJOINT, like the other personas).
        {"feedback_text": "I usually try to eat around 60-70 grams of carbs post meal, "
                          "this is too little carbs. So when i say one sweet potato it "
                          "usaully means more",
         "meal_text": "post workout ninja creami ice cream that has a scoop of whey "
                      "protein, ultra filtered 2% fat milk, a little greek yogurt, and "
                      "10g of zero sugar pudding mix. Then on the side i had one sweet potato"},
        {"feedback_text": "Way too much sourdough bread! One slice for me is usually "
                          "around 40-50 grams! I would also rarely eat more than 100g of "
                          "carbs in one meal",
         "meal_text": "two pieces of sourdough bread with three medium sized eggs, 3 "
                      "slices of turkey bacon, one serving of sugar free ketchup and "
                      "around 100g of cottage cheese"},
        {"feedback_text": "too many carbs in one meal. The outlier are the oats - i would "
                          "normally eat around 50g",
         "meal_text": "overnight oats with rolled oats, a banana, blueberries, greek "
                      "yogurt and some pbfit"},
        {"feedback_text": "way too much honey and sourdough bread. For a preworkout meal, "
                          "I try to get around 30-50 grams of carbs",
         "meal_text": "preworkout meal with a slice of sourdough bread, honey drizzled "
                      "on top, and one date"},
    ],
)


PERSONAS: dict[str, Persona] = {
    p.key: p for p in (RUNNER, BODYBUILDER, EVERYDAY, CREATOR)
}
DEFAULT_PERSONA = RUNNER.key


def get_persona(key: str | None) -> Persona:
    """The requested persona, falling back to the default for unknown keys."""
    return PERSONAS.get(key or DEFAULT_PERSONA, RUNNER)


# Backwards-compatible module-level aliases = the default (runner) persona, kept
# for the tests + scripts that import them directly.
DEMO_GOALS: dict[str, float] = RUNNER.goals
DEMO_GOAL_RATIONALE = RUNNER.goal_rationale
DEMO_MEALS: list[dict[str, Any]] = RUNNER.meals
DEMO_CONFIRMATIONS: list[dict[str, Any]] = RUNNER.confirmations
DEMO_FEEDBACK: list[dict[str, Any]] = RUNNER.feedback
